In [1]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


C:\Users\Asus\AppData\Local\Temp\ipykernel_32124\3214598455.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
import numpy as np
np.__version__


'1.26.4'

In [5]:
import numpy as np
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
import numpy as np
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
import numpy as np
np.full((3,5),1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [9]:
import numpy as np
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
import numpy as np
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
import numpy as np
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [24]:
#array.....
import numpy as np
x1 = np.array([1,2,3,4,5,6,4])
#print(x1)
x1
print(x1[0])
print(x1[5])
print(x1[-1]) #last index value
print(x1[-2]) #second last index value

1
6
4
6


In [8]:
import numpy as np
x1 = np.array([[3,7,5,5],[0,1,5,9],[3,0,5,0]])

print(x1[1,1])
print(x1[2,2])



1
5


In [4]:
import numpy as np
np.__version__

'1.26.4'